[build]
  command = "npm run build -w apps/frontend"
  publish = "apps/frontend/dist"

[functions]
  # Если Base directory = smartbook, то путь к api указываем от него
  directory = "api"

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
