[build]
  command = "npm run build -w apps/frontend"
  publish = "apps/frontend/dist"

[functions]
  # Просто указываем папку, Netlify сам поймет, что это TS и соберет их
  directory = "api"

[[redirects]]
  # Явное правило для вложенных путей типа /auth/me
  from = "/api/auth/:method"
  to = "/.netlify/functions/auth-:method"
  status = 200

[[redirects]]
  # Общее правило для всех остальных функций в корне /api
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Для React SPA
  from = "/*"
  to = "/index.html"
  status = 200
